import { ClerkProvider } from '@clerk/nextjs'

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ConvexClientProvider from '@/provider/ConvexClerkProvider';
import Navbar from '@/components/Navbar';
import Background from '@/components/Background';
import Footer from '@/components/Footer';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SweatSmart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY as string}>
      <ConvexClientProvider>
        <html lang="en">
          <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <Navbar/>
            <Background/>
            <main className='pt-24 flex-grow'>
              {children}
            </main>
            <Footer/>
          </body>
        </html>
      </ConvexClientProvider>
    </ClerkProvider>
  );
}
